### ISSUE TITLE
No response when click the left side menu on Mac Chrome

### ISSUE THREAD

**Issue by pjq** [devblogio-zz/devblog-feedback#6]
iMac
Chrome:
Version 35.0.1916.153

No response when click the left side menu on Mac Chrome, but it works on Safari.

**Comment by pjq** [comment]
And this tips always showing in the screen beside the left top logo.
"使用Github账号登录 (首次登录需邀请码)"

Sorry, it will disappear.

**Comment by goddyZhao** [comment]
ok, close it, then. Thanks
